#!/usr/bin/env python3
from pathlib import Path
from collections import defaultdict
import json, numpy as np
ROOT=Path(__file__).resolve().parents[1]
PAY=ROOT/'data/common_physical_chain/L24_N9_CHARGED_RANK6_PRECONTRACTION_PAYLOAD.npz'
OUT=ROOT/'results/COMMON_CONTRACTION_CHARACTERIZATION.json'
z=np.load(PAY,allow_pickle=False)
src=z['c10_edge_src'].astype(int); dst=z['c10_edge_dst'].astype(int); prob=z['c10_edge_probability'].astype(float)
rows=defaultdict(list)
for s,d,p in zip(src,dst,prob): rows[int(s)].append((int(d),float(p)))
row_res=float(max(abs(sum(p for _,p in v)-1.0) for v in rows.values()))
bc=z['su2_connected_branch_count'].astype(int); ba=z['su2_connected_branch_amplitudes']
branch=np.array([np.sum(np.abs(ba[i,:bc[i]])**2) for i in range(len(bc))])
su2_res=float(np.max(np.abs(branch-1.0)))
# Coherence-resolved witness built from an actual nontrivial C10 population transition.
cands=[(abs(p-.5),s,d,p) for s,v in rows.items() for d,p in v if 1e-12<p<1-1e-12]
_,s0,d0,p=min(cands); q=1-p
sp,sq=np.sqrt(p),np.sqrt(q)
U=np.array([[sp,sq],[sq,-sp]],complex)
P=np.array([[p,q],[q,p]],float)
Ks=[]
for j in range(2):
  for i in range(2):
    K=np.zeros((2,2),complex); K[j,i]=np.sqrt(P[j,i]); Ks.append(K)
def Ecoh(r): return U@r@U.conj().T
def Einc(r): return sum(K@r@K.conj().T for K in Ks)
basis_res=0.0
for i in range(2):
  e=np.zeros(2,complex); e[i]=1; r=np.outer(e,e.conj())
  basis_res=max(basis_res,float(np.max(np.abs(np.diag(Ecoh(r)).real-np.diag(Einc(r)).real))))
plus=np.array([1,1],complex)/np.sqrt(2); rp=np.outer(plus,plus.conj())
a=Ecoh(rp); b=Einc(rp)
trace_distance=float(.5*np.linalg.svd(a-b,compute_uv=False).sum())
sx=np.array([[0,1],[1,0]],complex)
coh_x=float(np.trace(sx@a).real); inc_x=float(np.trace(sx@b).real)
# Strict Kato checkpoint metadata.
kz=np.load(ROOT/'data/common_physical_chain/KATO_STRICT_K0_K12_48_CP.npz',allow_pickle=True)
meta=json.loads(str(kz['meta'].item()))
# Deterministic Riesz contour validation generated by this distribution.
rpath=ROOT/'results/RIESZ_NUMERICAL_VALIDATION.json'
r=json.loads(rpath.read_text())
riesz={
 'projector_action_fro_error':r['projector_fro_error'],
 'rho_fro_error':r['density_fro_error'],
 'retained_rank':r['retained_rank'],
 'uniform_gap_lower_bound':r['uniform_contour_gap'],
 'solve_count':r['linear_solves'],
 'worst_residual_norm':r['worst_linear_residual']
}
out={
 'classification':'FINITE_L24_COMMON_CONTRACTION_CHARACTERIZATION',
 'L':int(z['L']), 'moment_depth':int(z['n']), 'source_order':z['source_order'].tolist(),
 'serialized_primary_counts':{
   'links':int(len(z['links'])),'plaquettes':int(len(z['plaquettes'])),
   'su2_connected_pairs':int(len(z['su2_connected_pairs'])),
   'c10_nodes':int(len(z['c10_nodes'])),'c10_directed_edges':int(len(z['c10_edge_src']))},
 'normalization_residuals':{
   'c10_row_stochasticity_max_residual':row_res,
   'su2_branch_probability_max_residual':su2_res,
   'su2_branch_count_histogram':{str(int(k)):int(v) for k,v in zip(*np.unique(bc,return_counts=True))}},
 'coherence_resolved_c10_witness':{
   'source_node':int(s0),'destination_node':int(d0),'p':float(p),'one_minus_p':float(q),
   'basis_population_residual_between_two_CPTP_realizations':basis_res,
   'coherent_state_output_trace_distance':trace_distance,
   'sigma_x_expectation_channel_A':coh_x,'sigma_x_expectation_channel_B':inc_x,
   'interpretation':'The serialized population transition admits coherence-resolved CPTP realizations with distinct coherent-state responses. The common quantum contraction therefore carries the coherence map together with the population kernel.'},
 'strict_kato_checkpoint':{
   'dimension':int(meta['dim']),'nnz':int(meta['nnz']),'steps':int(meta['steps']),
   'ground_energy':float(meta['H_ground']),'gap':float(meta['H_gap']),
   'state_norm':float(np.linalg.norm(kz['v']))},
 'matrix_free_riesz_validation':riesz,
 'common_spectral_map':{
   'charged_fermions':'m_f=(hbar/(c^2 tau_*))*epsilon_f with epsilon_f read from the common charged rank-six matrix spectral measure',
   'quarks':'short-distance masses are read from the color-resolved renormalized chirality-changing inverse propagator in the declared scheme and scale',
   'neutrinos':'m_nu_i=(hbar/(c^2 tau_*))*sigma_i with sigma_i the active Takagi coordinates of the interacting neutral Nambu kernel',
   'matrix_moments':'C_n^(6)=V^dagger U^n V on the fixed source order (L1,L2,L3,R1,R2,R3)',
   'spectral_measure':'G_2 is the positive 6x6 matrix-valued spectral measure associated with the common frozen action and selected source subspace'
 },
 'operator_completion_principle':'The common spectral observable is evaluated after the coherence-resolved C10 map, boundary-to-path insertion, six-column embedding, charged causal-cone action and selected Riesz state are represented on one frozen finite-volume action.'
}
OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
print(json.dumps(out,indent=2,sort_keys=True))
